-- Add all missing columns to support the complete patient application form

ALTER TABLE public.temp_patient_applications
-- Personal Info
ADD COLUMN IF NOT EXISTS middle_name TEXT,
ADD COLUMN IF NOT EXISTS secondary_phone TEXT,
ADD COLUMN IF NOT EXISTS sex TEXT,
ADD COLUMN IF NOT EXISTS drivers_license TEXT,
ADD COLUMN IF NOT EXISTS marital_status TEXT,
ADD COLUMN IF NOT EXISTS home_street_address TEXT,
ADD COLUMN IF NOT EXISTS home_street_address_2 TEXT,
ADD COLUMN IF NOT EXISTS home_city TEXT,
ADD COLUMN IF NOT EXISTS home_state TEXT,
ADD COLUMN IF NOT EXISTS home_zip TEXT,
ADD COLUMN IF NOT EXISTS time_at_address TEXT,
ADD COLUMN IF NOT EXISTS rent_or_own TEXT,
ADD COLUMN IF NOT EXISTS previous_address TEXT,
ADD COLUMN IF NOT EXISTS previous_street_address TEXT,
ADD COLUMN IF NOT EXISTS previous_street_address_2 TEXT,
ADD COLUMN IF NOT EXISTS previous_city TEXT,
ADD COLUMN IF NOT EXISTS previous_state TEXT,
ADD COLUMN IF NOT EXISTS previous_zip TEXT,
ADD COLUMN IF NOT EXISTS emergency_contact_name TEXT,
ADD COLUMN IF NOT EXISTS emergency_contact_relationship TEXT,
ADD COLUMN IF NOT EXISTS emergency_contact_phone TEXT,
-- Employment
ADD COLUMN IF NOT EXISTS job_title TEXT,
ADD COLUMN IF NOT EXISTS work_phone TEXT,
ADD COLUMN IF NOT EXISTS length_of_employment TEXT,
ADD COLUMN IF NOT EXISTS monthly_net_income NUMERIC,
ADD COLUMN IF NOT EXISTS pay_frequency TEXT,
ADD COLUMN IF NOT EXISTS secondary_income_sources TEXT,
ADD COLUMN IF NOT EXISTS household_total_income NUMERIC,
ADD COLUMN IF NOT EXISTS spouse_employer TEXT,
ADD COLUMN IF NOT EXISTS spouse_income NUMERIC,
ADD COLUMN IF NOT EXISTS years_at_job NUMERIC,
-- Financial/Credit
ADD COLUMN IF NOT EXISTS credit_score NUMERIC,
ADD COLUMN IF NOT EXISTS recent_major_purchases TEXT,
-- Emotional/Decision
ADD COLUMN IF NOT EXISTS considering_treatment_time TEXT,
ADD COLUMN IF NOT EXISTS priority_preference TEXT,
ADD COLUMN IF NOT EXISTS primary_reason TEXT,
ADD COLUMN IF NOT EXISTS expected_procedures TEXT,
ADD COLUMN IF NOT EXISTS estimated_cost NUMERIC,
ADD COLUMN IF NOT EXISTS timeline_urgency TEXT,
ADD COLUMN IF NOT EXISTS ready_to_proceed TEXT,
ADD COLUMN IF NOT EXISTS insurance_coverage TEXT,
ADD COLUMN IF NOT EXISTS financing_preferences TEXT,
ADD COLUMN IF NOT EXISTS previous_treatment TEXT,
ADD COLUMN IF NOT EXISTS comfort_discussing_financing NUMERIC,
ADD COLUMN IF NOT EXISTS pain_level NUMERIC,
ADD COLUMN IF NOT EXISTS primary_motivator TEXT,
ADD COLUMN IF NOT EXISTS decision_making_style TEXT,
ADD COLUMN IF NOT EXISTS confidence_impact TEXT,
ADD COLUMN IF NOT EXISTS obstacles TEXT,
ADD COLUMN IF NOT EXISTS others_involved TEXT,
ADD COLUMN IF NOT EXISTS trust_factors TEXT,
ADD COLUMN IF NOT EXISTS negative_experiences TEXT,
ADD COLUMN IF NOT EXISTS target_payment_range TEXT,
ADD COLUMN IF NOT EXISTS commitment_level NUMERIC,
ADD COLUMN IF NOT EXISTS can_provide_proof BOOLEAN,
ADD COLUMN IF NOT EXISTS comfort_auto_debit BOOLEAN,
ADD COLUMN IF NOT EXISTS ready_for_call BOOLEAN,
ADD COLUMN IF NOT EXISTS ready_for_deposit BOOLEAN,
ADD COLUMN IF NOT EXISTS additional_info TEXT;