// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Using credentials to connect to Lovable Cloud backend
const SUPABASE_URL = "https://oqrvskdtvaykqkclpgew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xcnZza2R0dmF5a3FrY2xwZ2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNzA0NjksImV4cCI6MjA3NjY0NjQ2OX0.tWqCep9MA1yaB5qmrax3saC9NPbHUZy3_F6QjHE9ZFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});